### ISSUE TITLE
Zapier integration

### ISSUE THREAD

**Issue by maektwain** [InfluenceIO/influence.io#51]
**Is your feature request related to a problem? Please describe.**
Website owners use different kind of applications and integrations as well as connect with 3rd party service providers.  Integrating service providers is critical , its quite frustrating for us to have multiple apps which needs to be maintained for individual service providers. Integrating zapier is critical and can lead to multiple integrations directly through zapier platform.

**Describe the solution you'd like**
Single zapier app , which can collect customers/website/visitor data from different types of triggers which happen through zapier apps. Thus we need to connect our services via OAUTH and then allow the user to set the trackingID which then will collect consumer information via web-sockets.

**Describe alternatives you've considered**
I could not come up with any other alternative , describe if you have any.

**Additional context**
Customer flow while setting upon an integration with our product.

1. Customer logs inside 'Zapier App'
2. Customer selects an App, such as Mail chimp
<img width="800" alt="screen shot 2018-10-02 at 3 58 59 pm" src="https://user-images.githubusercontent.com/8274610/46343648-1a940800-c65c-11e8-87c2-cba29126f33b.png">
3. Then defines the triggers for the above app.
4. Customer connects the mail chimp account.
<img width="778" alt="screen shot 2018-10-02 at 4 00 20 pm" src="https://user-images.githubusercontent.com/8274610/46343718-4ca56a00-c65c-11e8-875d-24777948c7ec.png">
5. Customer needs to select the our useinfluence app.
6. Sets up the action.
7. Connect our account.
8. Logs data via the above mail chimp app.

**Comment by ShankyRana** [comment]
Estimated Efforts:
Authentication:- 8-9 hrs
Trigger:- 5 hrs
Action:- 5 hrs

**Comment by maektwain** [comment]
I think , Authentication can you describe what are you going to do in Authentication, like what needs to be done.? rest looks fine.

**Comment by ShankyRana** [comment]
Authentication:
-User will generate a API key in install pixel page and pass the key to Zap.
-Once the Key is authenticated Zap can log data through websocket.

Steps:
1. Generate API key.
2. Paste API key inside ZAP.
3. Authenticate API Key.
4. Publish ZAP.
